spring.application.name=currency-converter-api

exchange.api.base-url=https://v6.exchangerate-api.com/v6
exchange.api.key=${EXCHANGE_RATE_API_KEY}

spring.cache.cache-names=rates,codes
spring.cache.caffeine.spec=expireAfterWrite=30m,maximumSize=200

# lets Spring read your existing .env file during local dev (optional but convenient on Windows)
spring.config.import=optional:file:.env[.properties]